# Blocks per chunk
CHUNK_B_X = 16
CHUNK_B_Y = 256
CHUNK_B_Z = 16

# Chunks per region
REGION_C_X = 32
REGION_C_Z = 32

# Blocks per region
REGION_B_X = REGION_C_X * CHUNK_B_X
REGION_B_Y = CHUNK_B_Y
REGION_B_Z = REGION_C_Z * CHUNK_B_Z
REGION_B_TOTAL = REGION_B_X * REGION_B_Y * REGION_B_Z

# Classifier types
G_BACKGROUND = 0
G_AIR = 1
G_WATER = 2
G_SOLID = 3
G_TRANSPARENT = 4

# Identifier types
UNCHECKED = 0
UNCHANGED = 1
UNCHANGED2 = 0
WATERBLOCK = 2
AIRPOCKET = 3
SOLIDAREA = 4
