#############################
#############################
## UnitTest GitHub Actions ##
#############################
#############################
name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for unittest with tkinter
        run: |
          sudo apt-get update
          sudo apt-get install tk-dev python3-tk python3 python3.6 python3-pip python3-pytest
          sudo rm /usr/bin/python
          sudo ln -s /usr/bin/python3.6 /usr/bin/python
          sudo apt-get install xvfb
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install setuptools
          pip install anvil-parser
          pip install numpy
          pip install scipy
          pip install scikit-image
          pip install matplotlib
      - name: Run small test with pytest
        run: |
          # Start virtual display driver
          disp=:12
          screen=0
          geom=640x480x24
          exec Xvfb $disp -screen $screen $geom 2>/tmp/Xvfb.log &
          export DISPLAY=:12
          # Run TestSuites
          python3 -m pytest tests/test_small.py
      - name: Run big test with pytest
        run: |
          # Start virtual display driver
          disp=:12
          screen=0
          geom=640x480x24
          exec Xvfb $disp -screen $screen $geom 2>/tmp/Xvfb.log &
          export DISPLAY=:12
          # Run TestSuites
          python3 -m pytest tests/test_big.py
